# Generated by Django 5.0.6 on 2024-06-10 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_deliverylocations_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='ordered_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
